services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: prueba_tecnica
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data  # Para persistir los datos de la base de datos
    healthcheck:  # Verificación de salud para la base de datos
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      db:
        condition: service_healthy  # Espera hasta que la DB esté lista
    environment:
      DATABASE_HOST: db
      DATABASE_PORT: 5432
      DATABASE_USER: postgres
      DATABASE_PASSWORD: password
      DATABASE_NAME: prueba_tecnica
    volumes:
      - .:/app  # Volumen para código fuente de la aplicación
    command: yarn start:dev   # Comando para ejecutar la app

volumes:
  db_data:
